<?xml version="1.0"?>
<robot name="jackal" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931" />

  <xacro:arg name="namespace" default='' />
  <!-- Jackal properties -->
  <xacro:property name="wheelbase" value="0.262" />
  <xacro:property name="track" value="0.37559" />
  <xacro:property name="wheel_vertical_offset" value="0.0345" />
  <xacro:property name="footprint_vertical_offset" value="-0.0655" />

  <xacro:property name="wheel_radius" value="0.098" />
  <xacro:property name="wheel_width" value="0.040" />

  <xacro:property name="chassis_length" value="0.420" />
  <xacro:property name="chassis_width" value="0.310" />
  <xacro:property name="chassis_height" value="0.184" />

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120" />

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>
  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>

  <!-- Wheels macro -->
  <xacro:macro name="wheel" params="prefix mu *joint_pose">

    <link name="$(arg namespace)/${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <mesh filename="file://$(find jackal_description)/meshes/jackal-wheel.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.477"/>
        <inertia
          ixx="0.0013" ixy="0" ixz="0"
          iyy="0.0024" iyz="0"
          izz="0.0013"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="$(arg namespace)/chassis_link"/>
      <child link="$(arg namespace)/${prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <axis xyz="0 1 0" />
    </joint>

    <gazebo reference="${prefix}_wheel_link">
      <material>Gazebo/DarkGrey</material>
      <selfCollide>false</selfCollide>
      <!-- <mu1 value="${mu}"/>
      <mu2 value="${mu}"/>
      <kp value="10000000.0" />
      <kd value="1" />
      <fdir1 value="1 0 0"/> -->
    </gazebo>

  </xacro:macro>

  <!-- Links and joints -->
  <link name="$(arg namespace)/base_link"></link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="$(arg namespace)/base_link"/>
    <child link="$(arg namespace)/chassis_link" />
  </joint>

  <link name="$(arg namespace)/chassis_link">
    <visual>
      <origin xyz="0 0 ${footprint_vertical_offset}" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <mesh filename="file://$(find jackal_description)/meshes/jackal-base.stl"/>
      </geometry>
      <material name="dark_grey" />
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.012  0.002 0.067" rpy="0 0 0"/>
      <mass value="16.523"/>
      <inertia
        ixx="0.3136" ixy="-0.0008" ixz="0.0164"
        iyy="0.3922" iyz="-0.0009"
        izz="0.4485"/>
      </inertial>
  </link>

  <link name="$(arg namespace)/front_fender_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find jackal_description)/meshes/accessory_fender.stl"/>
      </geometry>
      <material name="yellow" />
    </visual>
  </link>

  <link name="$(arg namespace)/front_fender_accessory_link"/>
  <joint name="front_fender_accessory_joint" type="fixed">
    <origin xyz="0.25629 0 0.07455" rpy="${PI} 0 0" />
    <parent link="$(arg namespace)/front_fender_link" />
    <child link="$(arg namespace)/front_fender_accessory_link" />
  </joint>

  <joint name="front_fender_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="$(arg namespace)/chassis_link" />
    <child link="$(arg namespace)/front_fender_link" />
  </joint>

  <link name="$(arg namespace)/rear_fender_link">
    <visual>
      <geometry>
        <mesh filename="file://$(find jackal_description)/meshes/accessory_fender.stl"/>
      </geometry>
      <material name="yellow" />
    </visual>
  </link>

  <link name="$(arg namespace)/rear_fender_accessory_link"/>
  <joint name="rear_fender_accessory_joint" type="fixed">
    <origin xyz="0.25629 0 0.07455" rpy="${PI} 0 0" />
    <parent link="$(arg namespace)/rear_fender_link" />
    <child link="$(arg namespace)/rear_fender_accessory_link" />
  </joint>

  <joint name="rear_fender_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
    <parent link="$(arg namespace)/chassis_link" />
    <child link="$(arg namespace)/rear_fender_link" />
  </joint>

  <!-- Wheels links and joints -->
  <xacro:wheel prefix="front_left" mu="0.5">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="front_right" mu="0.5">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_left" mu="0.5">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>
  <xacro:wheel prefix="rear_right" mu="0.5">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:wheel>

  <!-- Default Internal IMU Link -->
  <link name="$(arg namespace)/imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="$(arg namespace)/chassis_link" />
    <child link="$(arg namespace)/imu_link" />
  </joint>

  <!-- Default NAVSAT Link -->
  <link name="$(arg namespace)/navsat_link">
    <visual>
      <geometry>
        <cylinder radius="0.026" length="0.016" />
      </geometry>
      <origin xyz="0 0 0.008" />
      <material name="black" />
    </visual>
  </link>
  <joint name="navsat_joint" type="fixed">
    <parent link="$(arg namespace)/chassis_link" />
    <child link="$(arg namespace)/navsat_link" />
    <origin xyz="-0.180 0.126 0.1815" />
  </joint>

  <link name="$(arg namespace)/mid_mount"></link>
  <joint name="mid_mount_joint" type="fixed">
    <parent link="$(arg namespace)/chassis_link" />
    <child link="$(arg namespace)/mid_mount" />
    <origin xyz="0 0 ${chassis_height}" />
  </joint>

  <link name="$(arg namespace)/rear_mount"></link>
  <joint name="rear_mount_joint" type="fixed">
    <parent link="$(arg namespace)/mid_mount" />
    <child link="$(arg namespace)/rear_mount" />
    <origin xyz="${-mount_spacing} 0 0" />
  </joint>

  <link name="$(arg namespace)/front_mount"></link>
  <joint name="front_mount_joint" type="fixed">
    <parent link="$(arg namespace)/mid_mount" />
    <child link="$(arg namespace)/front_mount" />
    <origin xyz="${mount_spacing} 0 0" />
  </joint>

  <xacro:include filename="$(find jackal_description)/urdf/accessories/camera_mount.urdf.xacro" />
  <xacro:camera_mount prefix="front" tilt="0.2" />

  <joint name="front_camera_mount_joint" type="fixed">
    <origin xyz="0 0 0"
            rpy="0 0 0" />
    <parent link="$(arg namespace)/front_mount" />
    <child link="$(arg namespace)/front_camera_mount" />
  </joint>

  <!-- Realsense D435 -->
  <xacro:arg name="use_nominal_extrinsics" default="true"/>
  <xacro:arg name="add_plug" default="true" />
  <xacro:arg name="use_mesh" default="true" />
  <xacro:include filename="$(find jackal_description)/urdf/accessories/_d435.urdf.xacro" />

  <xacro:sensor_d435 parent="front_camera_beam" use_nominal_extrinsics="$(arg use_nominal_extrinsics)"
                             name="camera" add_plug="$(arg add_plug)" use_mesh="$(arg use_mesh)">
    <origin xyz="0 0 0.04" rpy="0 0 0"/>
  </xacro:sensor_d435>

  <!-- Ouster OS1 32SR -->
  <xacro:include filename="$(find jackal_description)/urdf/accessories/OS1-32.urdf.xacro" />
  <xacro:OS1-32 parent="front_camera_mount" name="os_sensor">
    <origin xyz="0.0 0.0 0.10201" rpy="0 0 0"/>
  </xacro:OS1-32>

  <!-- Gazebo plugins -->
  <xacro:include filename="$(find jackal_description)/urdf/jackal.gazebo" />
  <xacro:control_gazebo/>

</robot>
